data:
  class_path: terratorch.datamodules.GenericMultiModalDataModule
  init_args:
    allow_missing_modalities: false
    allow_substring_file_names: true
    batch_size: 4
    channel_position: -3
    check_stackability: true
    concat_bands: false
    data_with_sample_dim: false
    drop_last: true
    expand_temporal_dimension: false
    means:
      DEM:
      - 338.315
      S1GRD:
      - -11.224
      - -18.978
      S2L2A:
      - 529.509
      - 622.422
      - 849.159
      - 889.618
      - 1280.02
      - 2572.048
      - 3249.194
      - 3357.392
      - 3518.104
      - 3533.077
      - 2808.764
      - 1955.034
    modalities:
    - S2L2A
    - S1GRD
    - DEM
    no_data_replace: 0.0
    no_label_replace: 0.0
    num_workers: 8
    pin_memory: false
    reduce_zero_label: false
    rgb_indices:
    - 3
    - 2
    - 1
    rgb_modality: S2L2A
    sample_replace: false
    shared_transforms: true
    skip_file_checks: false
    stds:
      DEM:
      - 57.13
      S1GRD:
      - 0.897
      - 1.098
      S2L2A:
      - 85.014
      - 107.36
      - 133.666
      - 192.031
      - 230.486
      - 314.053
      - 369.633
      - 373.084
      - 384.849
      - 378.25
      - 345.843
      - 295.994
    task: regression
    test_data_root:
      DEM: processed_data/weekly_24/processed_data_weekly_selected/DEM
      S1GRD: processed_data/weekly_24/processed_data_weekly_selected/S1GRD
      S2L2A: processed_data/weekly_24/processed_data_weekly_selected/S2L2A
    test_label_data_root: processed_data/weekly_24/processed_data_weekly_selected/yield_geotiffs
    test_split: processed_data/weekly_24/processed_data_weekly_selected/test_corn.txt
    train_data_root:
      DEM: processed_data/weekly_24/processed_data_weekly_selected/DEM
      S1GRD: processed_data/weekly_24/processed_data_weekly_selected/S1GRD
      S2L2A: processed_data/weekly_24/processed_data_weekly_selected/S2L2A
    train_label_data_root: processed_data/weekly_24/processed_data_weekly_selected/yield_geotiffs
    train_split: processed_data/weekly_24/processed_data_weekly_selected/train_corn.txt
    val_data_root:
      DEM: processed_data/weekly_24/processed_data_weekly_selected/DEM
      S1GRD: processed_data/weekly_24/processed_data_weekly_selected/S1GRD
      S2L2A: processed_data/weekly_24/processed_data_weekly_selected/S2L2A
    val_label_data_root: processed_data/weekly_24/processed_data_weekly_selected/yield_geotiffs
    val_split: processed_data/weekly_24/processed_data_weekly_selected/val_corn.txt
deploy_config_file: true
model:
  class_path: terratorch.tasks.PixelwiseRegressionTask
  init_args:
    freeze_backbone: false
    freeze_decoder: false
    freeze_head: false
    ignore_index: -1
    loss: mse
    lr: 0.001
    model_args:
      backbone: terramind_v1_base
      backbone_merge_method: mean
      backbone_modalities:
      - S2L2A
      - S1GRD
      - DEM
      backbone_pretrained: false
      decoder: UNetDecoder
      decoder_channels:
      - 512
      - 256
      - 128
      - 64
      head_dropout: 0.1
      necks:
      - indices:
        - 2
        - 5
        - 8
        - 11
        name: SelectIndices
      - name: ReshapeTokensToImage
        remove_cls_token: false
      - name: LearnedInterpolateToPyramidal
    model_factory: EncoderDecoderFactory
    plot_on_val: 10
out_dtype: int16
seed_everything: 42
trainer:
  accelerator: auto
  accumulate_grad_batches: 8
  barebones: false
  check_val_every_n_epoch: 1
  detect_anomaly: false
  devices: auto
  enable_autolog_hparams: true
  fast_dev_run: false
  inference_mode: true
  log_every_n_steps: 1
  logger: false
  max_epochs: 1000
  max_steps: -1
  num_nodes: 1
  overfit_batches: 0.0
  precision: 16-mixed
  reload_dataloaders_every_n_epochs: 0
  strategy: auto
  sync_batchnorm: false
  use_distributed_sampler: true
