seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
  - class_path: WandbLogger
    init_args:
      project: M3_soybean
      name: S12S_le_5_differentnorm_test
  callbacks:
  - class_path: ModelCheckpoint
    init_args:
      dirpath: output/soybean/M3/differentnorm/S12S_le_5/checkpoints
      monitor: val/loss
      mode: min
      save_top_k: 1
      save_last: true
      filename: best-{epoch:03d}_test
  - class_path: EarlyStopping
    init_args:
      monitor: val/loss
      patience: 75
      mode: min
      verbose: true
  - class_path: LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: RichProgressBar
  max_epochs: 1000
  log_every_n_steps: 1
  accumulate_grad_batches: 8
data:
  class_path: terratorch.datamodules.GenericMultiModalDataModule
  init_args:
    task: regression
    batch_size: 4
    num_workers: 8
    modalities:
    - S2L2A
    - S1GRD
    - SOIL
    rgb_modality: S2L2A
    rgb_indices:
    - 3
    - 2
    - 1
    train_data_root: &id001
      S2L2A: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/S2L2A
      S1GRD: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/S1GRD
      SOIL: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/SOIL
    train_label_data_root: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/yield_geotiffs
    val_data_root: *id001
    val_label_data_root: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/yield_geotiffs
    test_data_root: *id001
    test_label_data_root: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/yield_geotiffs
    train_split: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/train_soybean.txt
    val_split: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/val_soybean.txt
    test_split: /work/mech-ai-scratch/bgekim/project/ISA_Yield_Anirudha/ISA_Yield/processed_data/weekly_24/processed_data_weekly_24/test_soybean.txt
    expand_temporal_dimension: false
    no_label_replace: 0.0
    no_data_replace: 0
    means:
      S2L2A:
      - 1390.458
      - 1503.317
      - 1718.197
      - 1853.91
      - 2199.1
      - 2779.975
      - 2987.011
      - 3083.234
      - 3132.22
      - 3162.988
      - 2424.884
      - 1857.648
      S1GRD:
      - -12.599
      - -20.293
      SOIL:
      - 0.812
      - 0.787
      - 0.741
      - 20128.93
      - 21412.781
      - 253.445
      - 87.68
      - 182.086
      - 264.623
      - 335.16
    stds:
      S2L2A:
      - 2106.761
      - 2141.107
      - 2038.973
      - 2134.138
      - 2085.321
      - 1889.926
      - 1820.257
      - 1871.918
      - 1753.829
      - 1797.379
      - 1434.261
      - 1334.311
      S1GRD:
      - 5.195
      - 5.89
      SOIL:
      - 0.064
      - 0.071
      - 0.079
      - 6099.627
      - 6499.918
      - 44.726
      - 4.492
      - 15.991
      - 28.075
      - 41.569
model:
  class_path: terratorch.tasks.PixelwiseRegressionTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: terramind_v1_base
      backbone_pretrained: true
      backbone_modalities:
      - S2L2A
      - S1GRD
      - SOIL: 10
      backbone_merge_method: mean
      necks:
      - name: SelectIndices
        indices:
        - 2
        - 5
        - 8
        - 11
      - name: ReshapeTokensToImage
        remove_cls_token: false
      - name: LearnedInterpolateToPyramidal
      decoder: UNetDecoder
      decoder_channels:
      - 512
      - 256
      - 128
      - 64
      head_dropout: 0.1
    loss: mse
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    factor: 0.8
    patience: 25
    min_lr: 1.0e-06
